### ISSUE TITLE
Problem with laser blades going on head

### ISSUE THREAD

**Issue by IMaFishEatshark** [Iunius118/ToLaserBlade#16] opened 2021-12-07 04:24 UTC
I think it going on the head is funny but right clicking on the laser blade  causes it to swap with my helmet, 

PS i know it is WIP but i think a nether star or a beacon requiring recipe will be good

**Comment by Iunius118** [comment] 2021-12-07 05:39
That was an unexpected behavior, but it was funny and harmless, so I'll keep it as is.

**Comment by IMaFishEatshark** [comment] 2021-12-07 08:23
also eating with offhand with laser blade causes it to block with sword

**Comment by Iunius118** [comment] 2021-12-07 12:01
Thanks for the report.
I'm going to fix it so that the laser blade in offhand behaves well while player is using an item in the main hand.

**Comment by Iunius118** [comment] 2021-12-07 13:40
It will be fixed in next version.

![2021-12-07_22 19 26](https://user-images.githubusercontent.com/18502177/145038616-37f1af5e-6197-43f3-81ee-cd71fd524ef8.png)
![2021-12-07_23 31 43](https://user-images.githubusercontent.com/18502177/145048489-d70d07ec-f3c4-4814-b3ae-8a8f4a6bfa84.png)

**Comment by IMaFishEatshark** [comment] 2021-12-07 15:03
also can you keep the unicorn saber but make it togglable because placing down torches and eating makes helmet swap....

**Comment by Iunius118** [comment] 2021-12-07 16:22
Unfortunately, I couldn't reproduce the problem in my Forge 1.18 environment, so I'm thinking to fix it so that laser blades can't be worn as helmet.

**Comment by Iunius118** [comment] 2021-12-07 17:54
I have released [v1.18-5.1.1.1](https://www.curseforge.com/minecraft/mc-mods/tolaserblade/files/3553983). Please try it out.

**Closed as completed** 2022-01-27 09:43 UTC
Labels: bug
