### ISSUE TITLE
Tolaserblade not emitting light in 1.14.4 - possible solution?

### ISSUE THREAD

**Issue by GrifVindh** [Iunius118/ToLaserBlade#3] opened 2019-10-24 18:45 UTC
I've been trying to figure out why the 1.14.4 laser blade doesn't emit light like it does in 1.12.2. So I tracked down the optifine.properties file in both and compared them, and I found a pretty minor discrepancy.

In the 1.12.2 file:
items:laser_blade:15

In the 1.14.4 file:

items:laser_blade:15

The difference is that the 1.14.4 has a blank space above the listing
1.14.4:
[blank space]
items:laser_blade:15

I'm not a coder so I don't know how significant that is, but I do know that some scripts are very sensitive to spaces at the end of files. Is it possible that the blank line at the top of the file is fooling optifine into thinking the configuration file is empty?

I tried downloading the 1.14.4 code, removing the space in the config file, and compiling it myself, but I kept getting errors when I tried to run build.gradle, so I was unable to verify.

**Comment by Iunius118** [comment] 2019-10-25 06:09
OK, I sent an issue about the light emitting items to OptiFine, and it was tagged as a **bug** by OptiFine developer. So I think it will be fixed sooner or later.

**Comment by Iunius118** [comment] 2021-01-10 06:15
I have confirmed that the issue is caused by OptiFine, not by a syntax error of the properties, so there is nothing I can do to fix it.

**Closed as completed by Iunius118** 2021-01-10 06:15 UTC
Labels: wontfix
